In [1]:
import pandas as pd 
import numpy as np
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    "mssql+pyodbc://RAHUL\\SQLEXPRESS/alabs"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

In [3]:
account_df = pd.read_sql("select * from account",engine)
card_df = pd.read_sql("select * from card",engine)
client_df = pd.read_sql("select * from client",engine)
disp_df = pd.read_sql("select * from disp",engine)
district_df = pd.read_sql("select * from district",engine)
loan_df = pd.read_sql("select * from loan",engine)
orders_df = pd.read_sql("select * from orders",engine)
trnx_16_df = pd.read_sql("select * from trnx_16",engine)
trnx_17_df = pd.read_sql("select * from trnx_17",engine)
trnx_18_df = pd.read_sql("select * from trnx_18",engine)
trnx_19_df = pd.read_sql("select * from trnx_19_new",engine)
trnx_20_df = pd.read_sql("select * from trnx_20_new",engine)
trnx_21_df = pd.read_sql("select * from trnx_21_new",engine)

In [4]:
tables = {"account":account_df,"card":card_df,"client":client_df,"disp":disp_df,"district":district_df,"loan":loan_df,"orders":orders_df,
          "trnx_16":trnx_16_df,"trnx_17":trnx_17_df,"trnx_18":trnx_18_df,"trnx_19":trnx_19_df,"trnx_20":trnx_20_df,"trnx_21":trnx_21_df}

In [5]:
## Date Columns Clean
account_df["date"] = pd.to_datetime(account_df["date"])
loan_df["date"] = pd.to_datetime(loan_df["date"])
trnx_16_df["Date"] =pd.to_datetime(trnx_16_df["Date"])
trnx_17_df["Date"] =pd.to_datetime(trnx_17_df["Date"])
trnx_18_df["Date"] =pd.to_datetime(trnx_18_df["Date"])
trnx_19_df["Date"] =pd.to_datetime(trnx_19_df["Date"])
trnx_20_df["Date"] =pd.to_datetime(trnx_20_df["Date"])
trnx_21_df["Date"] =pd.to_datetime(trnx_21_df["Date"])

In [6]:
## amount payment clean 
trnx_16_df["amount"] = trnx_16_df["amount"].astype(float)
trnx_16_df["balance"] = trnx_16_df["balance"].astype(float)
trnx_17_df["amount"] = trnx_17_df["amount"].astype(float)
trnx_17_df["balance"] = trnx_17_df["balance"].astype(float)
trnx_18_df["amount"] = trnx_18_df["amount"].astype(float)
trnx_18_df["balance"] = trnx_18_df["balance"].astype(float)
trnx_19_df["amount"] = trnx_19_df["amount"].astype(float)
trnx_19_df["balance"] = trnx_19_df["balance"].astype(float)
trnx_20_df["amount"] = trnx_20_df["amount"].astype(float)
trnx_20_df["balance"] = trnx_20_df["balance"].astype(float)
trnx_21_df["amount"] = trnx_21_df["amount"].astype(float)
trnx_21_df["balance"] = trnx_21_df["balance"].astype(float)

In [7]:
orders_df["order_id"] = orders_df["order_id"].astype(int)
orders_df["account_id"] = orders_df["account_id"].astype(int)

In [8]:
text_cols = ["Type", "operation", "Purpose", "bank", "account_partern_id"]

for col in text_cols:
    for df in [
        trnx_16_df, trnx_17_df, trnx_18_df,
        trnx_19_df, trnx_20_df, trnx_21_df
    ]:
        df[col] = df[col].str.strip()

account_df["frequency"] = account_df["frequency"].str.strip()
account_df["Account_type"] = account_df["Account_type"].str.strip()

card_df["type"] = card_df["type"].str.strip()

disp_df["type"] = disp_df["type"].str.strip()

loan_df["status"] = loan_df["status"].str.strip()

orders_df["Bank_to"] = orders_df["Bank_to"].str.strip()

In [9]:
## duplicates 
for table_name , table in tables.items():
    print(table_name)
    print(table.duplicated().sum(),"\n")

account
0

card
0

client
0

disp
0

district
0

loan
0

orders
0

trnx_16
0

trnx_17
0

trnx_18
0

trnx_19
0

trnx_20
0

trnx_21
0

In [10]:
## Column name lower
for df in [account_df,card_df,client_df,disp_df,
           district_df,loan_df,orders_df,trnx_16_df,
           trnx_17_df, trnx_18_df,trnx_19_df, trnx_20_df, trnx_21_df]:
    df.columns = df.columns.str.lower()

In [11]:
for table_name ,table in tables.items():
    print(f" {table_name} {table.shape} ")

 account (4500, 5)
 card (892, 4)
 client (5369, 3)
 disp (5369, 4)
 district (77, 16)
 loan (682, 7)
 orders (6471, 5)
 trnx_16 (28205, 10)
 trnx_17 (91628, 10)
 trnx_18 (133022, 10)
 trnx_19 (196779, 10)
 trnx_20 (284409, 10)
 trnx_21 (314532, 10)

In [12]:
transactions_df = pd.concat([trnx_16_df,trnx_17_df,trnx_18_df,trnx_19_df,trnx_20_df,trnx_21_df],ignore_index=True)

### Client Table

In [135]:
client_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   client_id     5369 non-null   int64
 1   birth_number  5369 non-null   int64
 2   district_id   5369 non-null   int64
 3   YY            5369 non-null   object
 4   MM            5369 non-null   object
 5   DD            5369 non-null   object
 6   MM1           5369 non-null   object
 7   birth         5369 non-null   datetime64[ns]
 8   birth1        5369 non-null   datetime64[ns]
 9   gender        5369 non-null   object
dtypes: datetime64[ns](2), int64(3), object(5)
memory usage: 419.6+ KB

In [136]:
client_df.birth_number

0       706213
1       450204
2       406009
3       561201
4       605703
         ...
5364    456030
5365    430406
5366    680413
5367    626019
5368    535812
Name: birth_number, Length: 5369, dtype: int64

In [137]:
client_df["YY"] = client_df.birth_number.astype(str).str[0:2]
client_df["MM"] = client_df.birth_number.astype(str).str[2:4]
client_df["DD"] = client_df.birth_number.astype(str).str[4:6]

In [138]:
client_df["gender"] = client_df["MM"].astype(int).apply(lambda x: "Female" if x>50 else "Male")

In [139]:
client_df["MM1"] = (client_df["MM"].astype(int).apply(lambda x: (x-50) if x>50 else x)).astype(str)

In [140]:
client_df["birth"] = (pd.to_datetime(client_df["YY"]+client_df["MM1"] +client_df["DD"],format="%y%m%d"))

In [141]:
client_df["birth"]=(client_df["birth"].apply(lambda x : x-pd.offsets.DateOffset(years=100) if x >pd.Timestamp("2010") else x))

In [142]:
client_df["birth"].describe()

count                             5369
mean     1953-10-04 18:23:07.967964288
min                1911-08-20 00:00:00
25%                1940-11-26 00:00:00
50%                1954-06-03 00:00:00
75%                1968-07-18 00:00:00
max                1987-09-27 00:00:00
Name: birth, dtype: object

In [155]:
client_df["age"] = (2021 - client_df["birth"].dt.year)

In [156]:
client_df

      client_id      birth  gender  district_id  age
0             1 1970-12-13  Female           18   51
1             2 1945-02-04    Male            1   76
2             3 1940-10-09  Female            1   81
3             4 1956-12-01    Male            5   65
4             5 1960-07-03  Female            5   61
...         ...        ...     ...          ...  ...
5364      13955 1945-10-30  Female            1   76
5365      13956 1943-04-06    Male            1   78
5366      13968 1968-04-13    Male           61   53
5367      13971 1962-10-19  Female           67   59
5368      13998 1953-08-12  Female           74   68

[5369 rows x 5 columns]

In [157]:
client_df = client_df[['client_id','birth', 'gender', 'age','district_id']]
client_df.head()

   client_id      birth  gender  age  district_id
0          1 1970-12-13  Female   51           18
1          2 1945-02-04    Male   76            1
2          3 1940-10-09  Female   81            1
3          4 1956-12-01    Male   65            5
4          5 1960-07-03  Female   61            5

### Card tabel

In [14]:
card_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   card_id  892 non-null    int64
 1   disp_id  892 non-null    int64
 2   type     892 non-null    object
 3   issued   892 non-null    object
dtypes: int64(2), object(2)
memory usage: 28.0+ KB

In [15]:
print(card_df["type"].value_counts())

type
classic    659
junior     145
gold        88
Name: count, dtype: int64

In [186]:
card_df['issued_date'] = pd.to_datetime(card_df['issued'])+pd.offsets.DateOffset(years=23)

C:\Users\hp\AppData\Local\Temp\ipykernel_24692\42794535.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  card_df['issued_date'] = pd.to_datetime(card_df['issued'])+pd.offsets.DateOffset(years=23)

In [187]:
card_df['issued_date'].describe()

count                              892
mean     2020-09-19 01:36:51.659192832
min                2016-11-07 00:00:00
25%                2020-01-25 12:00:00
50%                2021-01-06 00:00:00
75%                2021-08-05 06:00:00
max                2021-12-29 00:00:00
Name: issued_date, dtype: object

### Account Table

In [16]:
account_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   account_id    4500 non-null   int64
 1   district_id   4500 non-null   int64
 2   frequency     4500 non-null   object
 3   date          4500 non-null   datetime64[ns]
 4   account_type  4500 non-null   object
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 175.9+ KB

In [17]:
for col in ["frequency","account_type"]:
    print(account_df[col].value_counts())

frequency
POPLATEK MESICNE      4167
POPLATEK TYDNE         240
POPLATEK PO OBRATU      93
Name: count, dtype: int64
account_type
Savings account    1533
NRI account        1522
Salary account     1445
Name: count, dtype: int64

In [68]:
account_df["date"] = account_df.date + pd.offsets.DateOffset(years=23)

In [70]:
account_df["date"].describe()

count                          4500
mean     2018-08-07 17:41:26.400000
min             2016-01-01 00:00:00
25%             2016-12-27 00:00:00
50%             2019-01-02 00:00:00
75%             2019-11-01 00:00:00
max             2020-12-29 00:00:00
Name: date, dtype: object

### Disp Table

In [19]:
disp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5369 entries, 0 to 5368
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   disp_id     5369 non-null   int64
 1   client_id   5369 non-null   int64
 2   account_id  5369 non-null   int64
 3   type        5369 non-null   object
dtypes: int64(3), object(1)
memory usage: 167.9+ KB

In [20]:
disp_df.type.value_counts()

type
OWNER    4500
USER      869
Name: count, dtype: int64

### District Table

In [21]:
district_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   district_id  77 non-null     int64
 1   a2           77 non-null     object
 2   a3           77 non-null     object
 3   a4           77 non-null     int64
 4   a5           77 non-null     int64
 5   a6           77 non-null     int64
 6   a7           77 non-null     int64
 7   a8           77 non-null     int64
 8   a9           77 non-null     int64
 9   a10          77 non-null     float64
 10  a11          77 non-null     int64
 11  a12          76 non-null     float64
 12  a13          77 non-null     float64
 13  a14          77 non-null     int64
 14  a15          76 non-null     float64
 15  a16          77 non-null     int64
dtypes: float64(4), int64(10), object(2)
memory usage: 9.8+ KB

In [22]:
district_df = district_df.rename(columns={"a2":"district name","a3":"region"})

In [23]:
district_df.region.value_counts()

region
south Moravia      14
central Bohemia    12
east Bohemia       11
north Moravia      11
west Bohemia       10
north Bohemia      10
south Bohemia       8
Prague              1
Name: count, dtype: int64

### Loan Table

In [167]:
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   loan_id     682 non-null    int64
 1   account_id  682 non-null    int64
 2   date        682 non-null    datetime64[ns]
 3   amount      682 non-null    int64
 4   duration    682 non-null    int64
 5   payments    682 non-null    float64
 6   status      682 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 37.4+ KB

In [168]:
loan_df.status.value_counts()

status
C    403
A    203
D     45
B     31
Name: count, dtype: int64

In [169]:
loan_df["date"] = loan_df["date"]+pd.offsets.DateOffset(years=23)

In [175]:
loan_df[['date','amount','duration','payments']].describe().T

,count,mean,min,25%,50%,75%,max,std
date,682,2019-09-30 01:07:33.958944256,2016-07-05 00:00:00,2018-07-04 12:00:00,2020-02-06 12:00:00,2020-12-12 12:00:00,2021-12-08 00:00:00,NaN
amount,682.0,151410.175953,4980.0,66732.0,116928.0,210654.0,590820.0,113372.40631
duration,682.0,36.492669,12.0,24.0,36.0,48.0,60.0,17.075219
payments,682.0,4190.664223,304.0,2477.0,3934.0,5813.5,9910.0,2215.830344

In [171]:
loan_df["loan_year"] = loan_df["date"].dt.year
loan_df["loan_month"] = loan_df["date"].dt.month

In [172]:
loan_df.loan_year.value_counts().sort_index()

loan_year
2016     20
2017    101
2018     90
2019    117
2020    196
2021    158
Name: count, dtype: int64

In [173]:
loan_df["problem_loan_flag"]= loan_df.status.isin(["B","D"]).astype(int)

In [174]:
loan_df["problem_loan_flag"].value_counts()

problem_loan_flag
0    606
1     76
Name: count, dtype: int64

### Orders Table

In [44]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6471 entries, 0 to 6470
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    6471 non-null   int64
 1   account_id  6471 non-null   int64
 2   bank_to     6471 non-null   object
 3   account_to  6471 non-null   int64
 4   amount      6471 non-null   float64
dtypes: float64(1), int64(3), object(1)
memory usage: 252.9+ KB

In [35]:
orders_df.bank_to.value_counts()

bank_to
Fio bank             531
Air Bank             521
Kameron bank         519
Hypotecni bank       515
Bank Creditas        511
Raiffeisen bank      500
Max bank             499
PPF Bank             496
Moneta Money Bank    487
Czech export bank    485
Trinity Bank         483
UniCredit Bank       466
J&T Bank             458
Name: count, dtype: int64

### Transactions Table

In [36]:
transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 10 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   trans_id            1048575 non-null  int64
 1   account_id          1048575 non-null  int64
 2   date                1048575 non-null  datetime64[ns]
 3   type                1048575 non-null  object
 4   operation           1048575 non-null  object
 5   amount              1048575 non-null  float64
 6   balance             1048575 non-null  float64
 7   purpose             516497 non-null   object
 8   bank                420858 non-null   object
 9   account_partern_id  295002 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 80.0+ MB

In [37]:
for col in ["type","operation","purpose","bank"]:
    print(transactions_df[col].value_counts(),"\n")

type
Withdrawal    648366
Credit        400209
Name: count, dtype: int64

operation
Withdrawal in cash            432377
Remittance to Another Bank    208283
Interest Credit               178663
Credit in cash                156320
Electronic funds transfer      65226
Credit card withdrawal          7706
Name: count, dtype: int64

purpose
Interest Credited       178663
Payment on Statement    155832
Household               118057
Old-age Pension          30338
Insurance Payment        18500
Loan Payment             13580
Sanction Interest         1527
Name: count, dtype: int64

bank
Sky Bank             147349
Fio bank              22285
Kameron bank          21720
Bank Creditas         21711
Air Bank              21582
Moneta Money Bank     21499
Trinity Bank          21293
Raiffeisen bank       21234
Max bank              21167
Czech export bank     21094
PPF Bank              20525
Hypotecni bank        20178
UniCredit Bank        19623
J&T Bank              19598
Name: count, dtype: int64

In [38]:
transactions_df[["date","amount","balance"]].describe().T

,count,mean,min,25%,50%,75%,max,std
date,1048575,2019-12-30 18:25:05.794434560,2016-01-01 00:00:00,2019-01-13 00:00:00,2020-04-06 00:00:00,2021-02-12 00:00:00,2021-12-19 00:00:00,NaN
amount,1048575.0,5942.153285,0.0,136.0,2100.0,6817.0,87400.0,9529.356611
balance,1048575.0,38456.72883,-41125.7,22388.4,33098.8,49502.2,209637.0,22068.506312

In [39]:
transactions_df["trnx_year"] = transactions_df["date"].dt.year
transactions_df["trnx_month"] = transactions_df["date"].dt.month
transactions_df["trnx_quarter"] = transactions_df["date"].dt.quarter

In [40]:
transactions_df["trnx_year"].value_counts().sort_index()

trnx_year
2016     28205
2017     91628
2018    133022
2019    196779
2020    284409
2021    314532
Name: count, dtype: int64

In [41]:
transactions_df["credit_amount"] = np.where(
    transactions_df["type"] == "Credit",
    transactions_df["amount"],
    0
)

transactions_df["withdrawal_amount"] = np.where(
    transactions_df["type"] == "Withdrawal",
    transactions_df["amount"],
    0
)

In [42]:
transactions_df[["credit_amount","withdrawal_amount"]].sum().astype(int)

credit_amount        3216335973
withdrawal_amount    3014457408
dtype: int64

account_df.to_csv("account_clean.csv",index=False)
card_df.to_csv("card_clean.csv",index=False)
client_df.to_csv("client_clean.csv",index=False)
disp_df.to_csv("disp_clean.csv",index=False)
district_df.to_csv("district_clean.csv",index=False)
loan_df.to_csv("loan_clean.csv",index=False)
orders_df.to_csv("orders_clean.csv",index=False)
transactions_df.to_csv("transactions_clean.csv",index=False)

account_df.to_sql("account_clean",con=engine,schema="clean",if_exists="replace",index=False)
card_df.to_sql("card_clean",con=engine,schema="clean",if_exists="replace",index=False)
client_df.to_sql("client_clean",con=engine,schema="clean",if_exists="replace",index=False)
disp_df.to_sql("disp_clean",con=engine,schema="clean",if_exists="replace",index=False)
district_df.to_sql("district_clean",con=engine,schema="clean",if_exists="replace",index=False)
loan_df.to_sql("loan_clean",con=engine,schema="clean",if_exists="replace",index=False)
orders_df.to_sql("orders_clean",con=engine,schema="clean",if_exists="replace",index=False)
transactions_df.to_sql("transactions_clean",con=engine,schema="clean",if_exists="replace",index=False)